FROM archlinux:base
RUN pacman -Sy --noconfirm archlinux-keyring && pacman -Syu --noconfirm base-devel desktop-file-utils xorg-server-xvfb xorg-xauth curl python python-websocket-client ttf-dejavu && pacman -Scc --noconfirm
