FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends dpkg-dev xz-utils ca-certificates desktop-file-utils xvfb xauth curl python3 python3-websocket fonts-dejavu-core && rm -rf /var/lib/apt/lists/*
